version: '3'
volumes:
  static_files:
services:
  python:
    #image: "python:3.7"
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    volumes:
      - static_files:/static_files
    ports:
      - 8000:8000
    command: gunicorn -w 4 basic_app.wsgi -b 0.0.0.0:8000
  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
      - static_files:/static_files
    ports:
      - 80:80
